### ISSUE TITLE
NameError: name 'AdvancedControls' is not defined.

### ISSUE THREAD

**Issue by pjwerneck** [lench4991/AdvancedControlsMod#5]
Running the latest versions (Besiege 0.42, ACM 1.5.0 and LenchScripterMod 2.2.1) on Linux Ubuntu 14.04.

The custom axis UI works after installing the LenchScripterMod and the IronPython dependencies, but `AdvancedControls` is not available in the namespace and I can't run the examples in the wiki.

**Comment by lenartbezek** [comment]
I see, it's basically the same bug that's causing it not to work without scripting mod present. Lack of any good testing will make this stuff happen.

Expect an update soon.

**Comment by lenartbezek** [comment]
https://github.com/lench4991/AdvancedControlsMod/releases/tag/v1.5.1
